name: Flutter CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner for CI/CD

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the code from GitHub repository

    - name: Set up Flutter
      uses: subosito/flutter-action@v2  # Set up Flutter environment
      with:
        flutter-version: '3.7.0'  # Specify Flutter version

    - name: Install dependencies
      run: flutter pub get  # Install Flutter dependencies

    - name: Run Flutter tests
      run: flutter test  # Run the Flutter unit tests

    - name: Build APK for Android
      run: flutter build apk --release  # Build APK for Android

    - name: Build iOS App (Optional)
      run: flutter build ios --release  # Build iOS app (if applicable)

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4  # Use updated version of the upload artifact action
      with:
        name: flutter-build
        path: build/
